# Generated by Django 3.1.2 on 2020-11-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='duration',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='reminder',
            name='name',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='reminder',
            name='start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
