# Generated by Django 3.1.2 on 2020-11-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20201103_0316'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='role_to_remind',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
