# Generated by Django 3.1.6 on 2021-02-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_reminder_role_to_remind'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='guild',
            field=models.IntegerField(default=0),
        ),
    ]
