# Generated by Django 3.1.6 on 2021-02-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0005_auto_20210226_0300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='role_to_remind',
            field=models.TextField(null=True),
        ),
    ]
