# Generated by Django 3.1.6 on 2021-02-26 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0006_auto_20210226_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='channel',
            field=models.IntegerField(default=0),
        ),
    ]
