# Generated by Django 3.1.6 on 2021-03-27 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0008_auto_20210226_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='channel',
            field=models.CharField(default=0, max_length=128),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='guild',
            field=models.CharField(default=0, max_length=128),
        ),
    ]
