# Generated by Django 3.1.4 on 2021-04-04 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0009_auto_20210327_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='guild',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
