# Generated by Django 3.1.6 on 2021-04-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0011_auto_20210404_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reminder',
            name='duration',
        ),
        migrations.AddField(
            model_name='reminder',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
